version: "1"
services:
  user_microservice:
    container_name: ${APP_NAME:?err}_user
    build:
      context: ./user_module
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  game_microservice:
    container_name: ${APP_NAME:?err}_game
    build:
      context: ./game_module
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      app_net:
        ipv4_address: 172.20.0.3

  score_microservice:
    container_name: ${APP_NAME:?err}_score
    build:
      context: ./score_module
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    networks:
      app_net:
        ipv4_address: 172.20.0.4

networks:
  app_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
